language: c
compiler:
  - gcc
  - clang
cache:
  directories:
  - $HOME/OpenBlasInstall
env:
  - TORCH_LUA_VERSION=LUAJIT21
  - TORCH_LUA_VERSION=LUA51
  - TORCH_LUA_VERSION=LUA52
sudo: false
addons:
  apt:
    packages:
    - cmake
    - gfortran
    - gcc-multilib
    - gfortran-multilib
    - liblapack-dev
    - build-essential
    - gcc
    - g++
    - curl
    - cmake
    - libreadline-dev
    - git-core
    - libqt4-core
    - libqt4-gui
    - libqt4-dev
    - libjpeg-dev
    - libpng-dev
    - ncurses-dev
    - imagemagick
    - libzmq3-dev
    - gfortran
    - unzip
    - gnuplot
    - gnuplot-x11
before_script:
- export ROOT_TRAVIS_DIR=$(pwd)
- export INSTALL_PREFIX=~/torch/install
- git clone https://github.com/torch/distro.git ~/torch --recursive
- cd ~/torch && git submodule update --init --recursive
- mkdir build && cd build
- cmake .. -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}" -DCMAKE_BUILD_TYPE=Release -DWITH_${TORCH_LUA_VERSION}=ON
- make && make install
- cd $ROOT_TRAVIS_DIR
- export LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:$LD_LIBRARY_PATH
- if [[ ! "$TORCH_LUA_VERSION" =~ "LUAJIT" ]]; then ${INSTALL_PREFIX}/bin/luarocks install luaffi; fi
script:
- ${INSTALL_PREFIX}/bin/luarocks make rocks/threads-scm-1.rockspec
- export PATH=${INSTALL_PREFIX}/bin:$PATH
- export TESTLUA=$(which luajit lua | head -n 1)
- ${TESTLUA} -lthreads -e "print('threads loaded succesfully')"
- cd test
- ${TESTLUA} test-threads.lua
- ${TESTLUA} test-threads-async.lua
- ${TESTLUA} test-threads-shared.lua
- ${TESTLUA} test-traceback.lua
- ${TESTLUA} test-threads-coroutine.lua
- ${TESTLUA} test-atomic.lua
