version: 2.3.0.{build}-test

shallow_clone: true

environment:
  LUAROCKS_VER: 2.3.0

  matrix:
  - LUA_VER: 5.1.5
  - LUA_VER: 5.2.4
  - LUA_VER: 5.3.1
  - LJ_VER: 2.0.4
  - LJ_VER: 2.1

init:
# Setup Lua development/build environment
# Make VS 2015 command line tools available
- call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%

install:
# Setup Lua development/build environment
- call .appveyor\install.bat

build_script:
- call .appveyor\build.bat

test_script:
- echo "Testing..."
- cd test
- call testing.bat
